### ISSUE TITLE
Update NPM deps

### ISSUE THREAD

**Issue by jimblue** [elisherer/webpack-dev-server-waitpage#18]
Hello,

Could your make a new release with updated NPM deps please?!

Thanks for this very nice plugin :)

**Comment by elisherer** [comment]
@jimblue , Do you mean webpack v5?

**Comment by elisherer** [comment]
Up in release 2.0.0 🚀 notice the new setup instructions

**Comment by jimblue** [comment]
Thank you, that was pretty fast 😄 !!
