### ISSUE TITLE
custom excludes support

### ISSUE THREAD

**Issue by Airkro** [elisherer/webpack-dev-server-waitpage#22]
Allow we replace `req.method !== 'GET'` at https://github.com/elisherer/webpack-dev-server-waitpage/blob/master/lib/index.js#L72

example: 

```js
webpackDevServerWaitpage(server, {
  excludes(req){
    return req.method !== 'GET' || req.url === 'xxx'
  }
})
```

**Comment by elisherer** [comment]
Would it be better to check for `req.headers.accept.includes('text/html')` (guessing you have an ajax GET call you don't want it to get the html back)?

**Comment by Airkro** [comment]
Yep, something like that, but might be more complicated. That's why I suggest provide a function, not an internal checker.

**Comment by elisherer** [comment]
@Airkro, Added `ignore` to [2.1.0](https://github.com/elisherer/webpack-dev-server-waitpage/releases/tag/2.1.0)

**Comment by Airkro** [comment]
The `wait until bundle finished` log shouldn't appear when something being ignored
