### ISSUE TITLE
webpack-serve deprecation

### ISSUE THREAD

**Issue by dvakatsiienko** [elisherer/webpack-dev-server-waitpage#9]
Considering [webpack-serve has been deprecated](https://github.com/webpack-contrib/webpack-serve#webpack-serve) is it possible to port this package to webpack-dev-server?
Or maybe someone knows an alternative?

**Comment by elisherer** [comment]
@dvakatsiienko , Done!

**Comment by dvakatsiienko** [comment]
wow, yo're pretty fast. awesome, thanx! :)
